# Generated by Django 4.1.3 on 2024-06-05 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_booking_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='expiry',
            field=models.DateField(null=True, verbose_name='expiry'),
        ),
    ]
